flowchart TD
mystart[start]
mystart-->set1[cin string]
set1-->set2[Input string]
set2-->set3[Reverse string: reverse the first and the last, the second and the last second and keep goings]
set3-->set4[Output string]
set4-->other1[end]